### ISSUE TITLE
Please Help me  , I can't execute your code : IndexError

### ISSUE THREAD

**Issue by ghost** [larics/nao-xo#23]
I have Ubuntu 14.04 and python 2.7 and opencv2 
I want to run this code : GitHub Link 
but if I do : python main_xo.py 
I get this error :
```

Traceback (most recent call last):
File "./main_xo.py", line 45, in <module>
    if not player.gameInit():   
File "/home/brm17/Desktop/nao-xo-master/nao_xo.py", line 697, in gameInit
    fieldFound = self.findField()
File "/home/brm17/Desktop/nao-xo-master/nao_xo.py", line 285, in findField
    self.intersections = self.imgproc.getIndexedIntersections(self.lines)
File "/home/brm17/Desktop/nao-xo-master/imgproc_xo.py", line 437, in getIndexedIntersections
    if self.checkIntersection(intersection, self.img_grayscale, 15, 1, 45):
File "/home/brm17/Desktop/nao-xo-master/imgproc_xo.py", line 298, in checkIntersection
    bin_rays[bin_ray] = bin_rays[bin_ray] + (255 - image[y, x])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
Segmentation fault (core dumped)
How to resolve this problem ?

**Comment by fpetric** [comment]
I will look into it when I get a hold of a NAO. Is it ok if I close #22  as it is pretty much the same issue?

**Comment by fpetric** [comment]
I have fixed the issues with this, at least on my setup (Ubuntu 16.04 LTS, Python 2.7.12, OpenCV 2.4.9) where it produced only warnings. If the issue persists on your system, let me know your setup so I can be of more help.

**Comment by ghost** [comment]
my setup : Ubuntu 14.04 , OpenCV2 of python , python 2.7 ... 
How to run this code ... i run this code but Nao he did nothing

**Comment by fpetric** [comment]
That setup should be fine. If you are not getting errors anymore, check the updated readme.

**Comment by ghost** [comment]
I had run this code, But the NAO didn't do anything!!!
I put a paper in frount of the Nao but he didn't react :(
Could you help me please!
what I must write on the paper 'X' or 'O'
thanks for your helping

**Comment by fpetric** [comment]
Can we move the discussion to a different thread? You can maybe open a new issue called: The robot does nothing so we have it organized for future reference

**Comment by ghost** [comment]
https://github.com/larics/nao-xo/issues/24
